version: '3'

services:
  client:
    build: .
    volumes:
      - .:/web-front
    command: yarn dev
    ports:
      - 8000:3000
    container_name: cafe-shares-web-front
  storybook:
    build: .
    volumes:
      - .:/web-front
    command: yarn storybook
    ports:
      - 6006:6006
    container_name: cafe-shares-storybook
