version: '3'

services:
  client:
    build: .
    volumes:
      - .:/app
    command: yarn dev
    ports:
      - 8000:3000
    container_name: cafe-search-app
  storybook:
    build: .
    volumes:
      - .:/app
    command: yarn storybook
    ports:
      - 6006:6006
    container_name: cafe-search-storybook
